### ISSUE TITLE
Code redundancy 

### ISSUE THREAD

**Issue by vuyanidaweti** [Vansh-Arora/java_playground#1]
accounts/src/accounts/Account.java

Why don't you use private access modifiers for your instance variables. 
This can increase your code encapsulation and the class privacy.

**Comment by Vansh-Arora** [comment]
Yeah, it increases the privacy but here I was just brushing up the basics.
Thanks though, I'll keep that in mind.

**Comment by vuyanidaweti** [comment]
Sweet.
